### ISSUE TITLE
MyElectric app shows yesterdays usage in 'Use Today'

### ISSUE THREAD

**Issue by sumnerboy12** [emoncms/app#1]
I am in NZ and have my Emoncms timezone set to NZST. The MyElectric bar graph looks good, with bars for each day, correctly labelled, and the current instantenous power is shown correctly as well. 

But the 'Use Today' value is displaying yesterdays total, not the current days total.

**Comment by glynhudson** [comment]
Did you manage to fix this? I remember some discussion with @JumpMaster on the forums

**Comment by JumpMaster** [comment]
I thought this has been fixed.

**Comment by sumnerboy12** [comment]
Yep apologies, I should have closed this issue. Not sure when but it has been working great for a while now!
