### ISSUE TITLE
Apps only list feeds with unique feed names

### ISSUE THREAD

**Issue by pb66** [emoncms/app#100]
see https://community.openenergymonitor.org/t/apps-feedlist-issues/11669?u=pb66

if two or more feeds have the same name (case sensitive) only the one with the highest id appears in the feedlist in the app config pages (tested on mysolarpv)

**Comment by TrystanLea** [comment]
I think this may well have been an issue for a while, the apps module arranges the feeds in an associative array by name rather than by node:name combination, needs a good bit of work to change in the code but obviously worthwhile.

**Comment by adminde** [comment]
This should be addressed in  #97.
I did not address the issues this raises regarding the auto selection though. And the visualization of the selected feed names looks still a bit strange, as the tag gets not yet displayed:

![emoncms-app-config|690x338](https://community.openenergymonitor.org/uploads/default/original/2X/b/ba2ca06cf84b88f3aaadb691175646c5454796a3.jpeg)

**Comment by TrystanLea** [comment]
This is now fixed in latest master
