### ISSUE TITLE
adding 'display as kW' in MyElectric2

### ISSUE THREAD

**Issue by emrysr** [emoncms/app#112]
I'vs noticed an issue on MySolarDivert, the exporting figure is very incorrect. The feed values has not changed between these two screenshots:

![Screenshot 2019-09-04 at 23 14 59](https://user-images.githubusercontent.com/758844/64295999-bf088380-cf6a-11e9-9439-d0cd0865d055.png)

![Screenshot 2019-09-04 at 23 15 14](https://user-images.githubusercontent.com/758844/64296007-c4fe6480-cf6a-11e9-909b-e7afe12abfba.png)

_Originally posted by @glynhudson in https://github.com/emoncms/app/pull/109#issuecomment-528113370_

**Comment by emrysr** [comment]
@glynhudson - this should fix it, however could you test with your data and let me know if the problem persists? 

thanks


these are screenshots with my 'fake' data:

[in Watts]
![delwedd](https://user-images.githubusercontent.com/1466013/64648540-04b5c800-d413-11e9-85cc-a517ff3ff7d3.png)

[in Kilowatts]
![delwedd](https://user-images.githubusercontent.com/1466013/64648580-14cda780-d413-11e9-9bb6-3177eecfb8eb.png)

**Comment by glynhudson** [comment]
It looks good apart from the divert figure is showing decimal places. 

I think it would be good if the values showed one decimal place e.g 1.6kW. This will still take up less space than 1600W. Would you like me to make a new issue for this?

**Comment by emrysr** [comment]
No that's fine. I'll create a pull request to this issue and re open it when I start
