### ISSUE TITLE
Kwh Use displays zero until first 24hrs has past 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/app#15]
Update: this bug has caused significant impact to user experience and support burden: https://community.openenergymonitor.org/t/split-phase-process-power1pluspower2/1935/29

When first setting up a system if the feed has been running for less than 24hrs the kwh per day on the MyElectric app displays zero when in fact we have used 2.01Kwh (see below). Feed selecting in MyElectric app is correct

![screenshot 2016-08-14 at 12 39 33](https://cloud.githubusercontent.com/assets/758844/17648887/0ac81efc-621d-11e6-9187-b5a82b05f59a.png)

**Comment by glynhudson** [comment]
https://community.openenergymonitor.org/t/ios-app-release/2134/16?u=glyn.hudson

**Comment by gerg7** [comment]
Hi,
Seems this is still not corrected - how about following code change in myelectric.php :
line 584:     
    if (daily.length>0) {
        usetoday_kwh = daily[daily.length-1][1];
    } **else {
        usetoday_kwh = feeds[use_kwh].value*1.0;
    }**
