### ISSUE TITLE
app_config mysql table is missing

### ISSUE THREAD

**Issue by yekorzh** [emoncms/app#3]
Hi,

I've installed apps on my own emoncms instance and noticed that app configs where not saved. After some digging in the app sources I found that the config gets written into app_config MySQL table, which was missing on my emoncms. I also couldn't find any place in the app code where emoncms would try creating that table in the database.

I suggest that AppConfig_model.php should create that table automatically if it doesn't exist.

**Comment by TrystanLea** [comment]
Hello yekorzh, the code for creating the table is in the core, you need to run the database update tool from the Admin tab in emoncms and then it should work ok.

**Comment by yekorzh** [comment]
Trystan,

Thank you, I guess it is better to mention somewhere in the doco then? I don't remember if I saw it anywhere...

Yegor

**Comment by glynhudson** [comment]
The database update will run automatically as part of an emonPi / emonBase update. If updating manually running a manual DB update as described above can be required.
