### ISSUE TITLE
unable to select myelectric config with last commit

### ISSUE THREAD

**Issue by airix1** [emoncms/app#5]
clicking on the config icon has no effect.  Running emoncms 9.0.  
Reverting back to previous commit works fine.

**Comment by Paul-Reed** [comment]
Same issue here following fresh install, also reported in forum by Bill Thomson. The previous commit - SHA 99ac28ce58bcccdaabe13862bba200f4d8c1f8f4 works fine for me too.

Paul

**Comment by glynhudson** [comment]
This has now been fixed
