### ISSUE TITLE
Cannot create a new app with the new navigation bar 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/app#73]
Testing the new nav bar I've noticed it doesn't seem possible to create a new app

**Comment by emrysr** [comment]
![delwedd](https://user-images.githubusercontent.com/1466013/55099510-bce6f280-50b7-11e9-986e-9c49886ddd9a.png)
an `+New` button has been added in my `dark-sidebar` branch. 
https://github.com/emrysr/app/tree/dark-sidebar

There is also a version merging this menu into the branch that both uses the dark sidebar and the app mobile resize:
https://github.com/emrysr/app/tree/dark-sidebar-mobile-resize
`remove top padding in mysolarpv to fit a single mobile view #72` https://github.com/emoncms/app/issues/72

@glynhudson - I'll create appropriate pull requests when we discuss the best route to merge these changes
