### ISSUE TITLE
SolarDivert: real-time solar gen figure incorrect

### ISSUE THREAD

**Issue by glynhudson** [emoncms/app#84]
The real-time solar PV generation figure seems to be incorrect. The graph is recording correctly e.g 

Solar is incorrectly displaying 1669W, the tooltip shows the actual generation of 1059W. My solar PV is 1200Wp therefore 1.6kW is impossible! 

![solar PV divert incorrect](https://user-images.githubusercontent.com/758844/57589719-0da69380-751e-11e9-91bd-50df1e2a74d6.png)

Can you replicate this issue @mattjgalloway?

**Comment by mattjgalloway** [comment]
Huh I’ve never seen this! Is it happening constantly? It’s weird how it’s exactly the same number as total use. And the numbers don’t add up at all. The export is calculated from the others, so I think the maths is correct but the display is wrong.

By any chance has the CSS ID of the solar been changed to be same ID as total use?

**Comment by glynhudson** [comment]
Mmm I've just checked the feed ID's for solar and total use, and they are unique. The solar is reading the same as house. 

I think the tool tip is slightly behind the real-time in this screenshot :

![Selection_183](https://user-images.githubusercontent.com/758844/57637640-d7135c00-75a3-11e9-879d-5d14f331ca04.jpg)

![Selection_184](https://user-images.githubusercontent.com/758844/57637890-73d5f980-75a4-11e9-8568-ba3ef4b9101e.jpg)


At least if you can't replicate the issue it could be just something effecting my system.

**Comment by mattjgalloway** [comment]
I don’t mean the IDs of the feeds, but of the HTML tag in the code.

Yeh I don’t have this problem but I also haven’t updated to the latest where there was the big refactor for the new menu etc.

**Comment by mattjgalloway** [comment]
@glynhudson Yeh, look here:
https://github.com/emoncms/app/blob/master/apps/OpenEnergyMonitor/mysolarpvdivert/mysolarpvdivert.php#L166

That should be:
```
<span class="generationnow">
```

Looks like it was broken in this commit:
https://github.com/emoncms/app/commit/4f0d030467734ec929013be983c6840b72f48ce4

PR incoming...

**Comment by mattjgalloway** [comment]
@glynhudson #85

**Comment by glynhudson** [comment]
Fix by https://github.com/emoncms/app/pull/85
