### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by reedy** [emoncms/app#92]
What's the license for this repo?

Is it AGPL-3.0-or-later as per https://github.com/emoncms/emoncms ?

**Comment by glynhudson** [comment]
Yes, it's the same as Emoncms https://github.com/emoncms/emoncms/blob/master/LICENSE.txt

**Comment by glynhudson** [comment]
Licence has been added https://github.com/emoncms/app/blob/master/LICENSE.txt
